// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inclusao_PedidoClienteProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inclusao_PedidoClienteProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201706172048556_Inclusao_PedidoClienteProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
