// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajuste_RelacionamentoFornecedorProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajuste_RelacionamentoFornecedorProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201706062226128_Ajuste_RelacionamentoFornecedorProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
