// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alteracao_Compra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteracao_Compra));
        
        string IMigrationMetadata.Id
        {
            get { return "201704210545243_Alteracao_Compra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
