// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criacao_Banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criacao_Banco));
        
        string IMigrationMetadata.Id
        {
            get { return "201704151958011_Criacao_Banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
