//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestrutura.CartaoDeCreditoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequisicaoSituacao", Namespace="http://schemas.datacontract.org/2004/07/CartaoDeCreditoService")]
    [System.SerializableAttribute()]
    public partial class RequisicaoSituacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdentificadorPagamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdentificadorPagamento {
            get {
                return this.IdentificadorPagamentoField;
            }
            set {
                if ((this.IdentificadorPagamentoField.Equals(value) != true)) {
                    this.IdentificadorPagamentoField = value;
                    this.RaisePropertyChanged("IdentificadorPagamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoRequisicaoSituacao", Namespace="http://schemas.datacontract.org/2004/07/CartaoDeCreditoService")]
    [System.SerializableAttribute()]
    public partial class RetornoRequisicaoSituacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infraestrutura.CartaoDeCreditoService.SituacaoPagamento SituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infraestrutura.CartaoDeCreditoService.SituacaoPagamento Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((this.SituacaoField.Equals(value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoPagamento", Namespace="http://schemas.datacontract.org/2004/07/CartaoDeCreditoService")]
    public enum SituacaoPagamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmAnalise = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoAprovado = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CartaoDeCreditoService.IServiceCartaoDeCredito")]
    public interface IServiceCartaoDeCredito {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCartaoDeCredito/ObterSituacaoPagamento", ReplyAction="http://tempuri.org/IServiceCartaoDeCredito/ObterSituacaoPagamentoResponse")]
        Infraestrutura.CartaoDeCreditoService.RetornoRequisicaoSituacao ObterSituacaoPagamento(Infraestrutura.CartaoDeCreditoService.RequisicaoSituacao requisicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCartaoDeCredito/ObterSituacaoPagamento", ReplyAction="http://tempuri.org/IServiceCartaoDeCredito/ObterSituacaoPagamentoResponse")]
        System.Threading.Tasks.Task<Infraestrutura.CartaoDeCreditoService.RetornoRequisicaoSituacao> ObterSituacaoPagamentoAsync(Infraestrutura.CartaoDeCreditoService.RequisicaoSituacao requisicao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCartaoDeCreditoChannel : Infraestrutura.CartaoDeCreditoService.IServiceCartaoDeCredito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCartaoDeCreditoClient : System.ServiceModel.ClientBase<Infraestrutura.CartaoDeCreditoService.IServiceCartaoDeCredito>, Infraestrutura.CartaoDeCreditoService.IServiceCartaoDeCredito {
        
        public ServiceCartaoDeCreditoClient() {
        }
        
        public ServiceCartaoDeCreditoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCartaoDeCreditoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCartaoDeCreditoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCartaoDeCreditoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Infraestrutura.CartaoDeCreditoService.RetornoRequisicaoSituacao ObterSituacaoPagamento(Infraestrutura.CartaoDeCreditoService.RequisicaoSituacao requisicao) {
            return base.Channel.ObterSituacaoPagamento(requisicao);
        }
        
        public System.Threading.Tasks.Task<Infraestrutura.CartaoDeCreditoService.RetornoRequisicaoSituacao> ObterSituacaoPagamentoAsync(Infraestrutura.CartaoDeCreditoService.RequisicaoSituacao requisicao) {
            return base.Channel.ObterSituacaoPagamentoAsync(requisicao);
        }
    }
}
